name: Create React App Workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.username }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn test -- --coverage
        env:
          CI: true
      - run: yarn run build
      - run: npm run deploy
