name: Environment Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  ubuntu-2004:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - shell: 'script -q -e -c "bash {0}"' # work around tty issues
        env:
          TERM: linux # fix tput for tty issue work around
        run: |
          bash --version
          bash -c "time env.test/bats/bin/bats  --print-output-on-failure --formatter tap env.test"
