name: Interactive Environment

on: [workflow_dispatch]

jobs:
  ubuntu-2004:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
